FROM ubuntu:latest

# RUN apt-get update && apt-get install -y python3 python3-pip python3-venv
RUN apt-get update && apt-get install -y openssh-server && apt-get install sudo
RUN mkdir /var/run/sshd

# WORKDIR /app

# COPY app/ /app/
RUN useradd -m -s /bin/bash admin
RUN echo 'admin:securepassword' | chpasswd



# Настройка ключей SSH
RUN mkdir /home/admin/.ssh
#COPY authorized_keys /home/admin/.ssh/
RUN chown -R admin:admin /home/admin/.ssh
RUN chmod 700 /home/admin/.ssh


#RUN chmod 600 /home/admin/.ssh/authorized_keys
# install Python packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*


RUN python3 -m venv venv
RUN ./venv/bin/pip install --upgrade pip
RUN ./venv/bin/pip install flask

# CMD ["./venv/bin/python", "app.py"]


EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
